#!/bin/sh

#Installation de chrome
explain "Installation de chrome"
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
tell sudo apt-get update
tell sudo apt-get install google-chrome-stable
