#!/bin/sh

#Installation ruby sass compass
explain "Installation de ruby"
  tell sudo apt-get install ruby-full bundler

explain "Installation de bundler"
  tell sudo gem install bundler

explain "Installation de Sass"
  tell sudo gem install sass
