#!/bin/sh

#Installation utilitaires
explain "Installation des utilitaires"
tell sudo apt-get remove vim-tiny
tell sudo apt-get remove unity-webapps-common
tell sudo apt-get install curl git-core vim

